-- =============================================================================
-- QUINDIOFLIX — Núcleo 5: Usuarios, Roles y Perfiles de Seguridad (Sección 3.5)
-- Ejecutar como DBA (SYS o SYSTEM)
-- =============================================================================

-- =============================================================================
-- 3.5.1 Creación de roles con privilegios diferenciados
-- =============================================================================

-- ROL_ADMIN: Administrador de la plataforma
CREATE ROLE ROL_ADMIN;
GRANT CREATE SESSION TO ROL_ADMIN;
-- CRUD en todas las tablas del esquema
GRANT SELECT, INSERT, UPDATE, DELETE ON QUINDIOFLIX.PLANES             TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON QUINDIOFLIX.CATEGORIAS         TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON QUINDIOFLIX.GENEROS            TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON QUINDIOFLIX.DEPARTAMENTOS      TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON QUINDIOFLIX.EMPLEADOS          TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON QUINDIOFLIX.JEFES_DEPARTAMENTO TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON QUINDIOFLIX.CONTENIDO          TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON QUINDIOFLIX.CONTENIDO_RELACIONADO TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON QUINDIOFLIX.CONTENIDO_GENEROS  TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON QUINDIOFLIX.TEMPORADAS         TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON QUINDIOFLIX.EPISODIOS          TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON QUINDIOFLIX.USUARIOS           TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON QUINDIOFLIX.PERFILES           TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON QUINDIOFLIX.REPRODUCCIONES     TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON QUINDIOFLIX.FAVORITOS          TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON QUINDIOFLIX.CALIFICACIONES     TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON QUINDIOFLIX.REPORTES           TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON QUINDIOFLIX.PAGOS              TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON QUINDIOFLIX.HISTORIAL_PLANES   TO ROL_ADMIN;
-- Ejecutar todos los procedimientos
GRANT EXECUTE ON QUINDIOFLIX.SP_REGISTRAR_USUARIO  TO ROL_ADMIN;
GRANT EXECUTE ON QUINDIOFLIX.SP_CAMBIAR_PLAN        TO ROL_ADMIN;
GRANT EXECUTE ON QUINDIOFLIX.SP_REPORTE_CONSUMO     TO ROL_ADMIN;
GRANT EXECUTE ON QUINDIOFLIX.SP_ELIMINAR_CUENTA     TO ROL_ADMIN;
GRANT EXECUTE ON QUINDIOFLIX.SP_REFRESCAR_VISTAS    TO ROL_ADMIN;
GRANT EXECUTE ON QUINDIOFLIX.FN_CALCULAR_MONTO      TO ROL_ADMIN;
GRANT EXECUTE ON QUINDIOFLIX.FN_CONTENIDO_RECOMENDADO TO ROL_ADMIN;

-- ROL_ANALISTA: Analista de datos / gerencia (solo lectura + reportes)
CREATE ROLE ROL_ANALISTA;
GRANT CREATE SESSION TO ROL_ANALISTA;
GRANT SELECT ON QUINDIOFLIX.PLANES             TO ROL_ANALISTA;
GRANT SELECT ON QUINDIOFLIX.CATEGORIAS         TO ROL_ANALISTA;
GRANT SELECT ON QUINDIOFLIX.GENEROS            TO ROL_ANALISTA;
GRANT SELECT ON QUINDIOFLIX.DEPARTAMENTOS      TO ROL_ANALISTA;
GRANT SELECT ON QUINDIOFLIX.EMPLEADOS          TO ROL_ANALISTA;
GRANT SELECT ON QUINDIOFLIX.CONTENIDO          TO ROL_ANALISTA;
GRANT SELECT ON QUINDIOFLIX.CONTENIDO_GENEROS  TO ROL_ANALISTA;
GRANT SELECT ON QUINDIOFLIX.TEMPORADAS         TO ROL_ANALISTA;
GRANT SELECT ON QUINDIOFLIX.EPISODIOS          TO ROL_ANALISTA;
GRANT SELECT ON QUINDIOFLIX.USUARIOS           TO ROL_ANALISTA;
GRANT SELECT ON QUINDIOFLIX.PERFILES           TO ROL_ANALISTA;
GRANT SELECT ON QUINDIOFLIX.REPRODUCCIONES     TO ROL_ANALISTA;
GRANT SELECT ON QUINDIOFLIX.CALIFICACIONES     TO ROL_ANALISTA;
GRANT SELECT ON QUINDIOFLIX.REPORTES           TO ROL_ANALISTA;
GRANT SELECT ON QUINDIOFLIX.PAGOS              TO ROL_ANALISTA;
GRANT SELECT ON QUINDIOFLIX.HISTORIAL_PLANES   TO ROL_ANALISTA;
-- Acceso a vistas materializadas
GRANT SELECT ON QUINDIOFLIX.MV_POPULARIDAD_CONTENIDO TO ROL_ANALISTA;
GRANT SELECT ON QUINDIOFLIX.MV_INGRESOS_MENSUALES    TO ROL_ANALISTA;
-- Procedimientos de reportes
GRANT EXECUTE ON QUINDIOFLIX.SP_REPORTE_CONSUMO   TO ROL_ANALISTA;
GRANT EXECUTE ON QUINDIOFLIX.FN_CALCULAR_MONTO    TO ROL_ANALISTA;

-- ROL_SOPORTE: Soporte al cliente
CREATE ROLE ROL_SOPORTE;
GRANT CREATE SESSION TO ROL_SOPORTE;
GRANT SELECT ON QUINDIOFLIX.USUARIOS         TO ROL_SOPORTE;
GRANT SELECT ON QUINDIOFLIX.PERFILES         TO ROL_SOPORTE;
GRANT SELECT ON QUINDIOFLIX.PLANES           TO ROL_SOPORTE;
GRANT SELECT ON QUINDIOFLIX.HISTORIAL_PLANES TO ROL_SOPORTE;
GRANT SELECT, INSERT, UPDATE ON QUINDIOFLIX.PAGOS TO ROL_SOPORTE;
GRANT SELECT ON QUINDIOFLIX.REPORTES         TO ROL_SOPORTE;
GRANT EXECUTE ON QUINDIOFLIX.SP_CAMBIAR_PLAN TO ROL_SOPORTE;

-- ROL_CONTENIDO: Gestor de catálogo
CREATE ROLE ROL_CONTENIDO;
GRANT CREATE SESSION TO ROL_CONTENIDO;
GRANT SELECT, INSERT, UPDATE, DELETE ON QUINDIOFLIX.CONTENIDO           TO ROL_CONTENIDO;
GRANT SELECT, INSERT, UPDATE, DELETE ON QUINDIOFLIX.CONTENIDO_RELACIONADO TO ROL_CONTENIDO;
GRANT SELECT, INSERT, UPDATE, DELETE ON QUINDIOFLIX.CONTENIDO_GENEROS   TO ROL_CONTENIDO;
GRANT SELECT, INSERT, UPDATE, DELETE ON QUINDIOFLIX.TEMPORADAS          TO ROL_CONTENIDO;
GRANT SELECT, INSERT, UPDATE, DELETE ON QUINDIOFLIX.EPISODIOS           TO ROL_CONTENIDO;
GRANT SELECT, INSERT, UPDATE, DELETE ON QUINDIOFLIX.GENEROS             TO ROL_CONTENIDO;
GRANT SELECT, INSERT, UPDATE, DELETE ON QUINDIOFLIX.CATEGORIAS          TO ROL_CONTENIDO;
GRANT SELECT ON QUINDIOFLIX.REPRODUCCIONES  TO ROL_CONTENIDO;
GRANT SELECT ON QUINDIOFLIX.CALIFICACIONES  TO ROL_CONTENIDO;

-- =============================================================================
-- 3.5.2 Crear usuarios Oracle y asignar roles
-- =============================================================================

-- Usuario administrador
CREATE USER USR_ADMIN_QF IDENTIFIED BY "Admin@QF2026!"
    DEFAULT TABLESPACE TBS_QUINDIOFLIX
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON TBS_QUINDIOFLIX;
GRANT ROL_ADMIN TO USR_ADMIN_QF;

-- Usuario analista
CREATE USER USR_ANALISTA_QF IDENTIFIED BY "Analista@QF2026!"
    DEFAULT TABLESPACE TBS_QUINDIOFLIX
    TEMPORARY TABLESPACE TEMP
    QUOTA 10M ON TBS_QUINDIOFLIX;
GRANT ROL_ANALISTA TO USR_ANALISTA_QF;

-- Usuario soporte
CREATE USER USR_SOPORTE_QF IDENTIFIED BY "Soporte@QF2026!"
    DEFAULT TABLESPACE TBS_QUINDIOFLIX
    TEMPORARY TABLESPACE TEMP
    QUOTA 5M ON TBS_QUINDIOFLIX;
GRANT ROL_SOPORTE TO USR_SOPORTE_QF;

-- Usuario gestor de contenido
CREATE USER USR_CONTENIDO_QF IDENTIFIED BY "Contenido@QF2026!"
    DEFAULT TABLESPACE TBS_QUINDIOFLIX
    TEMPORARY TABLESPACE TEMP
    QUOTA 20M ON TBS_QUINDIOFLIX;
GRANT ROL_CONTENIDO TO USR_CONTENIDO_QF;

-- =============================================================================
-- 3.5.3 Demostración de restricciones por rol
-- =============================================================================

-- Conectar como USR_SOPORTE_QF e intentar eliminar un usuario (NO permitido)
-- CONNECT USR_SOPORTE_QF/"Soporte@QF2026!";
-- DELETE FROM QUINDIOFLIX.USUARIOS WHERE id_usuario = 1;
-- Resultado esperado: ORA-01031: insufficient privileges

-- Conectar como USR_ANALISTA_QF e intentar insertar contenido (NO permitido)
-- CONNECT USR_ANALISTA_QF/"Analista@QF2026!";
-- INSERT INTO QUINDIOFLIX.CONTENIDO (titulo, tipo, ...) VALUES (...);
-- Resultado esperado: ORA-01031: insufficient privileges

-- Conectar como USR_CONTENIDO_QF e intentar ver pagos (NO permitido)
-- CONNECT USR_CONTENIDO_QF/"Contenido@QF2026!";
-- SELECT * FROM QUINDIOFLIX.PAGOS;
-- Resultado esperado: ORA-00942: table or view does not exist

-- =============================================================================
-- 3.5.4 Perfiles de recursos (PROFILE)
-- =============================================================================

-- Perfil para usuarios de aplicación (analistas, soporte, contenido)
CREATE PROFILE PROF_APP_USER LIMIT
    SESSIONS_PER_USER          3          -- máximo 3 sesiones concurrentes
    CPU_PER_SESSION            UNLIMITED
    CPU_PER_CALL               3000       -- máximo 30 segundos por llamada
    CONNECT_TIME               480        -- máximo 8 horas de conexión
    IDLE_TIME                  30         -- desconectar tras 30 min de inactividad
    LOGICAL_READS_PER_SESSION  UNLIMITED
    LOGICAL_READS_PER_CALL     100000
    FAILED_LOGIN_ATTEMPTS      5          -- bloquear tras 5 intentos fallidos
    PASSWORD_LOCK_TIME         1/24       -- bloqueo por 1 hora
    PASSWORD_LIFE_TIME         90         -- contraseña expira cada 90 días
    PASSWORD_REUSE_TIME        365        -- no reutilizar contraseña por 1 año
    PASSWORD_REUSE_MAX         5          -- no reutilizar las últimas 5 contraseñas
    PASSWORD_VERIFY_FUNCTION   DEFAULT;

-- Perfil para el administrador (más permisivo pero con control)
CREATE PROFILE PROF_ADMIN LIMIT
    SESSIONS_PER_USER          2
    CPU_PER_SESSION            UNLIMITED
    CONNECT_TIME               UNLIMITED
    IDLE_TIME                  60
    FAILED_LOGIN_ATTEMPTS      3
    PASSWORD_LOCK_TIME         1/12       -- bloqueo por 2 horas
    PASSWORD_LIFE_TIME         60
    PASSWORD_REUSE_TIME        365
    PASSWORD_REUSE_MAX         10
    PASSWORD_VERIFY_FUNCTION   DEFAULT;

-- Asignar perfiles a usuarios
ALTER USER USR_ADMIN_QF     PROFILE PROF_ADMIN;
ALTER USER USR_ANALISTA_QF  PROFILE PROF_APP_USER;
ALTER USER USR_SOPORTE_QF   PROFILE PROF_APP_USER;
ALTER USER USR_CONTENIDO_QF PROFILE PROF_APP_USER;

-- Verificar configuración
SELECT username, profile, account_status, default_tablespace
FROM DBA_USERS
WHERE username IN ('USR_ADMIN_QF','USR_ANALISTA_QF','USR_SOPORTE_QF','USR_CONTENIDO_QF');

SELECT grantee, granted_role, admin_option
FROM DBA_ROLE_PRIVS
WHERE grantee IN ('USR_ADMIN_QF','USR_ANALISTA_QF','USR_SOPORTE_QF','USR_CONTENIDO_QF');

